### ISSUE TITLE
离线消息如何实现

### ISSUE THREAD

**Issue by chenzylab** [yujuncai/Tia-notify#1]
您好，请求离线消息如何实现，有无此计划

**Comment by yujuncai** [comment]
离线消息实现只需要在未推送成功时写入表中type标记为离线，再设计一个命令如 history-message，在登陆后进入到聊天页，首先发送这个命令即可，量大可以最近的100条，用户上翻翻页第二个100条，然后标记为正常即可

**Comment by yujuncai** [comment]
并且代码其实实现了一部分了
![image](https://github.com/yujuncai/Tia-notify/assets/9441501/868bf0d7-d7a2-4342-a16b-7c28a1866cbc)
![1709034480368](https://github.com/yujuncai/Tia-notify/assets/9441501/3e75bc55-fd05-4c7b-ae28-fd0608a0caa2)
![1709034435564](https://github.com/yujuncai/Tia-notify/assets/9441501/1a828a12-db8c-4866-9784-4069c54ea08b)
